version: '2'
services:
    node:
        image: node
        volumes:
            - ./:/usr/src/app
        working_dir: /usr/src/app
        ports:
            - "3000"
        links:
            - redis
        env_file:
            - ./.env
        depends_on:
            - "mongo"
        command: npm start
    mongo:
        image: tutum/mongodb
        ports:
            - "27017:27017"
            - "28017:28017"
        env_file:
            - ./.env
        volumes:
            - ./.data/db:/data/db
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - node:node
    redis:
        image: redis
        ports:
            - "6379:6379"
